// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH_Bmmac7zEfi_8WTT7bJPMsUnR_xsWcE',
    appId: '1:143923436966:web:f71e277d583d0f65878367',
    messagingSenderId: '143923436966',
    projectId: 'healthcare-app-8000d',
    authDomain: 'healthcare-app-8000d.firebaseapp.com',
    storageBucket: 'healthcare-app-8000d.firebasestorage.app',
    measurementId: 'G-3ZZ1FE7XDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs_CP9-nICa6TXbBQUxZkszLFTpRMbbEc',
    appId: '1:143923436966:android:76f3a55bc26844a0878367',
    messagingSenderId: '143923436966',
    projectId: 'healthcare-app-8000d',
    storageBucket: 'healthcare-app-8000d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbStaJdK8JpB2SyeRfddSRyk8xwAyUbvw',
    appId: '1:143923436966:ios:ad391011954bb72b878367',
    messagingSenderId: '143923436966',
    projectId: 'healthcare-app-8000d',
    storageBucket: 'healthcare-app-8000d.firebasestorage.app',
    iosBundleId: 'com.example.healthcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbStaJdK8JpB2SyeRfddSRyk8xwAyUbvw',
    appId: '1:143923436966:ios:ad391011954bb72b878367',
    messagingSenderId: '143923436966',
    projectId: 'healthcare-app-8000d',
    storageBucket: 'healthcare-app-8000d.firebasestorage.app',
    iosBundleId: 'com.example.healthcareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH_Bmmac7zEfi_8WTT7bJPMsUnR_xsWcE',
    appId: '1:143923436966:web:5e4e1459572610d2878367',
    messagingSenderId: '143923436966',
    projectId: 'healthcare-app-8000d',
    authDomain: 'healthcare-app-8000d.firebaseapp.com',
    storageBucket: 'healthcare-app-8000d.firebasestorage.app',
    measurementId: 'G-ZWP9WF4D6Y',
  );
}
